apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: udagram-frontend-deployment 
spec: 
  selector: 
    matchLabels: 
      app: udagram-frontend 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: udagram-frontend 
    spec: 
      containers: 
      - name: udagram-frontend 
        image: tusharkathuria/udagram-frontend
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"  
        ports: 
        - containerPort: 80