kind: Service 
apiVersion: v1 
metadata: 
  name: udagram-frontend-service 
spec: 
  selector: 
    app: udagram-frontend
  ports: 
  - name: "8100"
    port: 8100
    targetPort: 80
  type: LoadBalancer 